Populate Glass Onion demo buckets (#938)
**Summary:**

This PR adds and modifies a set of GitHub Actions workflows for
populating an S3 bucket with demo metadata and text content which is
suitable for consumption by Glass Onion. The major changes are depicted
below:

```mermaid
graph TD
  A((Build QML Branch - Dev))
  B[Build QML Branch]
  C((Build Website - JSON))
  D[Upload JSON to S3]
  E((Build Website - Text))
  F[Upload Text to S3]

  A -->|HTML| B
  C -->|JSON| B
  C --> D
  E -->|Text, Skip Execution| B
  E --> F

  style E stroke:#0F0
  style F stroke:#0F0
  linkStyle 3 stroke:#0F0,stroke-width:1px;
  linkStyle 4 stroke:#0F0,stroke-width:1px;
```

Specifically,

* A new reusable workflow `upload-text.yml` is added which uploads text
versions of each demo to a Glass Onion demos bucket. The metadata of
each demo is also included and concatenated into a single file to
minimize network calls.
* A new workflow `build-text.yml` is added which builds the text
versions of each demo and calls `upload-text.yml`
* The `deploy-demos-to-prod.yml` workflow is updated to also populate
the production Glass Onion demos buckets.
* The `build-branch.yml` workflow is updated to include a
`skip_execution_of_examples` option.

The PR also contributes a custom Sphinx extension to fix this error from
Sphinx Gallery when building `text` demos:
```
Exception occurred:
  File "/home/runner/work/qml/qml/venv/lib/python3.9/site-packages/sphinx/writers/text.py", line 1178, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: imgsgnode
```

**Relevant references:**

* [Here](https://github.com/PennyLaneAI/qml/actions/runs/6407577527/) is
an example of a successful run.

**Possible Drawbacks:**

* Additional GitHub Actions resources are needed to run the new
workflows.

**Related GitHub Issues:**

None.