Added warning to hybrid jobs demo (v0.32 compatibility).  (#979)
Braket has v0.32, and there's picking / unpickling going on behind the
scenes in the demo which causes issues when running this demo with
another PennyLane version, say v0.33:

```
...
"/opt/braket/code/customer_code/extracted/decorator_job_w_t6ad3e/entry_point.py", line 63, in <module>
    recovered = cloudpickle.loads(b'…')
AttributeError: Can't get attribute '_expand_transform_finite_diff' on <module 'pennylane.gradients.finite_difference' from '/usr/local/lib/python3.10/site-packages/pennylane/gradients/finite_difference.py'>
Process exited with code: 1
```